name: ddsp-pytorch
channels:
  - defaults
dependencies:
  - python==3.7
  - torchvision
  - cudatoolkit=11.1
  - torchaudio
  - pytorch
  - pyyaml
  - librosa
  - crepe
  - tqdm
  - tensorflow
  - tensorboard=1.15
  - einops
prefix: /homes/cdl01/.conda/envs/ddsp-pytorch

